server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: residence
          uri: lb://residence
          predicates:
            - Path=/residence/**
          filters:
            - StripPrefix=1
        - id: authentication
          uri: lb://authentication
          predicates:
            - Path=/**
